
package com.gsww.gsrhc.hrdi.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JkfpSoapServiceService", targetNamespace = "http://soap.hrdi.gsrhc.gsww.com/", wsdlLocation = "http://10.85.40.82:8083/arms-server/service/jkfp?wsdl")
public class JkfpSoapServiceService
    extends Service
{

    private final static URL JKFPSOAPSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException JKFPSOAPSERVICESERVICE_EXCEPTION;
    private final static QName JKFPSOAPSERVICESERVICE_QNAME = new QName("http://soap.hrdi.gsrhc.gsww.com/", "JkfpSoapServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.85.40.82:8083/arms-server/service/jkfp?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        JKFPSOAPSERVICESERVICE_WSDL_LOCATION = url;
        JKFPSOAPSERVICESERVICE_EXCEPTION = e;
    }

    public JkfpSoapServiceService() {
        super(__getWsdlLocation(), JKFPSOAPSERVICESERVICE_QNAME);
    }

    public JkfpSoapServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JKFPSOAPSERVICESERVICE_QNAME, features);
    }

    public JkfpSoapServiceService(URL wsdlLocation) {
        super(wsdlLocation, JKFPSOAPSERVICESERVICE_QNAME);
    }

    public JkfpSoapServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JKFPSOAPSERVICESERVICE_QNAME, features);
    }

    public JkfpSoapServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JkfpSoapServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JkfpSoapService
     */
    @WebEndpoint(name = "JkfpSoapServicePort")
    public JkfpSoapService getJkfpSoapServicePort() {
        return super.getPort(new QName("http://soap.hrdi.gsrhc.gsww.com/", "JkfpSoapServicePort"), JkfpSoapService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JkfpSoapService
     */
    @WebEndpoint(name = "JkfpSoapServicePort")
    public JkfpSoapService getJkfpSoapServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.hrdi.gsrhc.gsww.com/", "JkfpSoapServicePort"), JkfpSoapService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JKFPSOAPSERVICESERVICE_EXCEPTION!= null) {
            throw JKFPSOAPSERVICESERVICE_EXCEPTION;
        }
        return JKFPSOAPSERVICESERVICE_WSDL_LOCATION;
    }

}
