
package com.gsww.gsrhc.hrdi.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JkfpSoapService", targetNamespace = "http://soap.hrdi.gsrhc.gsww.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JkfpSoapService {


    /**
     * 
     * @param jkfpQuery
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod(operationName = "JkfpQuery", action = "http://soap.hrdi.gsrhc.gsww.com/JkfpQuery")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "JkfpQuery", targetNamespace = "http://soap.hrdi.gsrhc.gsww.com/", className = "com.gsww.gsrhc.hrdi.soap.JkfpQuery")
    @ResponseWrapper(localName = "JkfpQueryResponse", targetNamespace = "http://soap.hrdi.gsrhc.gsww.com/", className = "com.gsww.gsrhc.hrdi.soap.JkfpQueryResponse")
    public String jkfpQuery(
        @WebParam(name = "JkfpQuery", targetNamespace = "http://soap.hrdi.gsrhc.gsww.com/")
        String jkfpQuery)
        throws Exception_Exception
    ;

}
