server:
  port: 8085
  servlet:
    context-path: /zookeeper-demo
spring:
  application:
    name: zookeeper-demo
  main:
    banner-mode: console
  datasource:
    druid:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://10.18.33.229:3306/dev_yxwg?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: yxy_wg
        password: yxy_wg
        initial-size: 5
        min-idle: 10
        max-active: 1000
        max-wait: 60000
        time-between-eviction-runs-millis: 28800
        min-evictable-idle-time-millis: 30000
        validation-query: SELECT 1 FROM DUAL
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    database: 0
    host: 10.18.33.158
    port: 6379
    password:
logging:
  path: logs/
  level:
    root: info