server:
  servlet:
    context-path: /boot-consumer
  port: 8082
spring:
  application:
    name: boot-consumer
  thymeleaf:
    cache: false
  session:
    store-type: none
  main:
    banner-mode: console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.18.33.229:3306/dev_yxwg?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: fjzl
    password: fjzl
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    database: 0
    host: 10.18.33.158
    port: 6379
    password:
  rabbitmq:
    host: 192.168.92.50
    port: 5672
    username: admin
    password: admin
logging:
  level:
    root: info
  path: logs/
