server:
  servlet:
    context-path: /boot-producer
  port: 8083
spring:
  application:
    name: boot-producer
  thymeleaf:
    cache: false
  session:
    store-type: none
  main:
    banner-mode: console
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://xxxxxx:3306/dev_yxwg?characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: xxxx
    password: xxxxx
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  redis:
    database: 0
    host: xxxxx
    port: 6379
    password:
  rabbitmq:
    host: xxxxxxx
    port: 5672
    username: admin
    password: admin
    virtual-host: /test_mq
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
logging:
  level:
    root: info
  path: logs/
